/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
    interface TypesConfig {
        ParamParsers: never;
    }
}

declare module 'vue-router/auto-routes' {
    /**
     * Route name map generated by vue-router
     */
    export interface RouteNamedMap {
        '/': RouteRecordInfo<
            '/',
            '/',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/exercises': RouteRecordInfo<
            '/exercises',
            '/exercises',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/habits': RouteRecordInfo<
            '/habits',
            '/habits',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/measurements': RouteRecordInfo<
            '/measurements',
            '/measurements',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/notes': RouteRecordInfo<
            '/notes',
            '/notes',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/running': RouteRecordInfo<
            '/running',
            '/running',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/settings': RouteRecordInfo<
            '/settings',
            '/settings',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/strength': RouteRecordInfo<
            '/strength',
            '/strength',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/tasks': RouteRecordInfo<
            '/tasks',
            '/tasks',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/workout-logs': RouteRecordInfo<
            '/workout-logs',
            '/workout-logs',
            Record<never, never>,
            Record<never, never>,
            never
        >;
        '/workout-routines': RouteRecordInfo<
            '/workout-routines',
            '/workout-routines',
            Record<never, never>,
            Record<never, never>,
            never
        >;
    }

    /**
     * Route file to route info map by vue-router.
     * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
     *
     * Each key is a file path relative to the project root with 2 properties:
     * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
     * - views: names of nested views (can be passed to <RouterView name="...">)
     *
     * @internal
     */
    export interface _RouteFileInfoMap {
        'src/pages/index.vue': {
            routes: '/';
            views: never;
        };
        'src/pages/exercises.vue': {
            routes: '/exercises';
            views: never;
        };
        'src/pages/habits.vue': {
            routes: '/habits';
            views: never;
        };
        'src/pages/measurements.vue': {
            routes: '/measurements';
            views: never;
        };
        'src/pages/notes.vue': {
            routes: '/notes';
            views: never;
        };
        'src/pages/running.vue': {
            routes: '/running';
            views: never;
        };
        'src/pages/settings.vue': {
            routes: '/settings';
            views: never;
        };
        'src/pages/strength.vue': {
            routes: '/strength';
            views: never;
        };
        'src/pages/tasks.vue': {
            routes: '/tasks';
            views: never;
        };
        'src/pages/workout-logs.vue': {
            routes: '/workout-logs';
            views: never;
        };
        'src/pages/workout-routines.vue': {
            routes: '/workout-routines';
            views: never;
        };
    }

    /**
     * Get a union of possible route names in a certain route component file.
     * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
     *
     * @internal
     */
    export type _RouteNamesForFilePath<FilePath extends string> =
        _RouteFileInfoMap extends Record<FilePath, infer Info>
            ? Info['routes']
            : keyof RouteNamedMap;
}

export {};
