#!/usr/bin/env bash
#
# Build a minimal .app bundle that launches the dev stack, so it can live in
# the Dock (which only accepts .app bundles, not .command scripts).
#
# The bundle is a thin wrapper: its executable opens scripts/launch.command in
# Terminal, so you still get the server logs and Ctrl-C. It is generated rather
# than committed because it hard-codes the absolute path to this checkout.
#
#   ./scripts/install-dock-app.sh              install to ~/Applications
#   ./scripts/install-dock-app.sh /Applications   or somewhere else
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${1:-$HOME/Applications}"
APP="$DEST/Personal Tracker Dev.app"
UI_URL="http://localhost:3099"

# Distinct from the packaged Electron build's com.stevefurches.personaltracker,
# so Launch Services treats them as different apps.
BUNDLE_ID="com.stevefurches.personaltracker.dev"

[ -x "$ROOT/scripts/launch.command" ] ||
    { echo "missing $ROOT/scripts/launch.command" >&2; exit 1; }

mkdir -p "$DEST"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Personal Tracker Dev</string>
  <key>CFBundleDisplayName</key><string>Personal Tracker Dev</string>
  <key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
  <key>CFBundleVersion</key><string>1</string>
  <key>CFBundleShortVersionString</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>launcher</string>
  <key>CFBundleIconFile</key><string>icon</string>
  <key>NSHighResolutionCapable</key><true/>
</dict>
</plist>
PLIST

# The bundle's executable. Uses absolute paths throughout: an app launched from
# the Dock gets a minimal PATH, so nothing here may be assumed to be on it.
cat > "$APP/Contents/MacOS/launcher" <<LAUNCHER
#!/bin/bash
#
# Generated by scripts/install-dock-app.sh — edit that, not this.
#
# Already running? Just show it, rather than starting a second stack that would
# fail on the port check.
if /usr/bin/curl -fsS -o /dev/null --max-time 2 "$UI_URL" 2>/dev/null; then
    exec /usr/bin/open "$UI_URL"
fi

exec /usr/bin/open -a Terminal "$ROOT/scripts/launch.command"
LAUNCHER
chmod +x "$APP/Contents/MacOS/launcher"

if [ -f "$ROOT/ui/electron/icons/icon.icns" ]; then
    cp "$ROOT/ui/electron/icons/icon.icns" "$APP/Contents/Resources/icon.icns"
else
    echo "warn: ui/electron/icons/icon.icns not found — the app gets a blank icon" >&2
fi

# Nudge Finder/Launch Services so the icon and name are picked up immediately
# rather than after a relaunch.
touch "$APP"
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister \
    -f "$APP" >/dev/null 2>&1 || true

echo "Installed: $APP"
echo
echo "To add it to the Dock: open the folder in Finder and drag the app to the"
echo "Dock, or launch it once and right-click its Dock icon → Options → Keep in Dock."
echo
echo "  open \"$DEST\""
