/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddEditRunDialog: typeof import('./src/components/AddEditRunDialog.vue')['default']
    AddEditTaskDialog: typeof import('./src/components/AddEditTaskDialog.vue')['default']
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    ConfirmDeleteDialog: typeof import('./src/components/ConfirmDeleteDialog.vue')['default']
    DurationRangeFilter: typeof import('./src/components/DurationRangeFilter.vue')['default']
    ExerciseFormDialog: typeof import('./src/components/ExerciseFormDialog.vue')['default']
    ExerciseHistoryDialog: typeof import('./src/components/ExerciseHistoryDialog.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    LogWorkoutDialog: typeof import('./src/components/LogWorkoutDialog.vue')['default']
    NotFoundState: typeof import('./src/components/NotFoundState.vue')['default']
    NumberRangeFilter: typeof import('./src/components/NumberRangeFilter.vue')['default']
    PaceRangeFilter: typeof import('./src/components/PaceRangeFilter.vue')['default']
    RouteMap: typeof import('./src/components/RouteMap.vue')['default']
    RouteOutline: typeof import('./src/components/RouteOutline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RunBadges: typeof import('./src/components/RunBadges.vue')['default']
    RunningCalendar: typeof import('./src/components/RunningCalendar.vue')['default']
    SectionLayout: typeof import('./src/components/SectionLayout.vue')['default']
    StatTileGrid: typeof import('./src/components/StatTileGrid.vue')['default']
    WeeklyProgressList: typeof import('./src/components/WeeklyProgressList.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
