/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    ExerciseHistoryDialog: typeof import('./src/components/ExerciseHistoryDialog.vue')['default']
    LoadingState: typeof import('./src/components/LoadingState.vue')['default']
    LogWorkoutDialog: typeof import('./src/components/LogWorkoutDialog.vue')['default']
    RouteMap: typeof import('./src/components/RouteMap.vue')['default']
    RouteOutline: typeof import('./src/components/RouteOutline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
