/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommandPalette: typeof import('./src/components/CommandPalette.vue')['default']
    ExerciseHistoryDialog: typeof import('./src/components/ExerciseHistoryDialog.vue')['default']
    NoteDueBadges: typeof import('./src/components/NoteDueBadges.vue')['default']
    NoteRow: typeof import('./src/components/NoteRow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
