/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/exercises': RouteRecordInfo<
      '/exercises',
      '/exercises',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/running': RouteRecordInfo<
      '/running',
      '/running',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasks': RouteRecordInfo<
      '/tasks',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workout-logs': RouteRecordInfo<
      '/workout-logs',
      '/workout-logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workout-routines': RouteRecordInfo<
      '/workout-routines',
      '/workout-routines',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/exercises.vue': {
      routes:
        | '/exercises'
      views:
        | never
    }
    'src/pages/running.vue': {
      routes:
        | '/running'
      views:
        | never
    }
    'src/pages/tasks.vue': {
      routes:
        | '/tasks'
      views:
        | never
    }
    'src/pages/workout-logs.vue': {
      routes:
        | '/workout-logs'
      views:
        | never
    }
    'src/pages/workout-routines.vue': {
      routes:
        | '/workout-routines'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
